services:
    php:
        build: .
        ports:
            - "8080:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - ../:/app # ✅ Monte la racine du projet dans /app
        working_dir: /app
        environment:
            - SERVER_NAME=localhost
            - DATABASE_URL=mysql://symfony:symfony@mysql:3306/app?serverVersion=8.4
        depends_on:
            - mysql

    mysql:
        image: mysql:8.4
        environment:
            MYSQL_DATABASE: app
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
            MYSQL_ROOT_PASSWORD: root
        # ports:
        #     - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
